---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.appName }}-ingress"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-{{ .Values.environment }}"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    acme.cert-manager.io/http01-ingress-class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.appName }}
            port:
              number: {{ .Values.service.port }}
  tls:
    - hosts:
      - {{ .Values.domain }}
      secretName: "letsencrypt-{{ .Values.environment }}-secretname"
