apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "letsencrypt-{{ .Values.environment }}"
  namespace: tfg-dev
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dlopezlo@gmail.com
    privateKeySecretRef:
      name: "letsencrypt-{{ .Values.environment }}"
    solvers:
      - http01:
          ingress:
            class: nginx
